on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: cd ${{ github.workspace }} && echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Zip files
        run: cd ${{ github.workspace }} && zip -x ".*" -r MarvalSoftware.Plugins.Teams.zip .
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.vars.outputs.sha_short }}
          prerelease: false
          title: Release ${{ steps.vars.outputs.sha_short }}
          files: ${{ github.workspace }}/MarvalSoftware.Plugins.Teams.zip
